[project]
name = "mc809-comp-distribuida"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "grpcio",
    "pandas",
    "matplotlib",
    "grpcio-tools",
    "scikit-learn",
    "tensorflow",
    "keras",
    "keras-tuner",
    "ray",
    "ipykernel",
    "ucimlrepo",
    "seaborn"
]