# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_payload.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'data_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_payload.proto\x12\tfederated\x1a\x1bgoogle/protobuf/empty.proto\"Z\n\x0b\x44\x61taPayload\x12\x15\n\routput_vector\x18\x01 \x03(\x01\x12\x0f\n\x07pair_id\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\x05\x12\x10\n\x08\x63lass_id\x18\x04 \x01(\x05\x32R\n\x11SimilarityService\x12=\n\x0b\x43ompareData\x12\x16.federated.DataPayload\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAPAYLOAD']._serialized_start=62
  _globals['_DATAPAYLOAD']._serialized_end=152
  _globals['_SIMILARITYSERVICE']._serialized_start=154
  _globals['_SIMILARITYSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
