# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fit_train.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fit_train.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66it_train.proto\x12\x0c\x66ittraingrpc\")\n\x06Sample\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x01\x12\r\n\x05label\x18\x02 \x01(\x05\"2\n\tDataInput\x12%\n\x07samples\x18\x01 \x03(\x0b\x32\x14.fittraingrpc.Sample\"-\n\x0bTrainOutput\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x01\x12\x0c\n\x04time\x18\x02 \x01(\x01\"5\n\x0cPredictInput\x12%\n\x07samples\x18\x01 \x03(\x0b\x32\x14.fittraingrpc.Sample\"$\n\rPredictOutput\x12\x13\n\x0bpredictions\x18\x01 \x03(\x05\x32I\n\x08\x46itTrain\x12=\n\x05Train\x12\x17.fittraingrpc.DataInput\x1a\x19.fittraingrpc.TrainOutput\"\x00\x32O\n\x07Predict\x12\x44\n\x07Predict\x12\x1a.fittraingrpc.PredictInput\x1a\x1b.fittraingrpc.PredictOutput\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fit_train_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLE']._serialized_start=33
  _globals['_SAMPLE']._serialized_end=74
  _globals['_DATAINPUT']._serialized_start=76
  _globals['_DATAINPUT']._serialized_end=126
  _globals['_TRAINOUTPUT']._serialized_start=128
  _globals['_TRAINOUTPUT']._serialized_end=173
  _globals['_PREDICTINPUT']._serialized_start=175
  _globals['_PREDICTINPUT']._serialized_end=228
  _globals['_PREDICTOUTPUT']._serialized_start=230
  _globals['_PREDICTOUTPUT']._serialized_end=266
  _globals['_FITTRAIN']._serialized_start=268
  _globals['_FITTRAIN']._serialized_end=341
  _globals['_PREDICT']._serialized_start=343
  _globals['_PREDICT']._serialized_end=422
# @@protoc_insertion_point(module_scope)
