services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/app.Dockerfile
    volumes:
      - ..:/mc809 - Comp Distribuida:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    gpus: all