# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import splitlearning_pb2 as splitlearning__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in splitlearning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SendActivationsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendClientActivations = channel.unary_unary(
                '/splitlearning.SendActivations/SendClientActivations',
                request_serializer=splitlearning__pb2.Activations.SerializeToString,
                response_deserializer=splitlearning__pb2.Activations.FromString,
                _registered_method=True)


class SendActivationsServicer:
    """Missing associated documentation comment in .proto file."""

    def SendClientActivations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendActivationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendClientActivations': grpc.unary_unary_rpc_method_handler(
                    servicer.SendClientActivations,
                    request_deserializer=splitlearning__pb2.Activations.FromString,
                    response_serializer=splitlearning__pb2.Activations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.SendActivations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearning.SendActivations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SendActivations:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendClientActivations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SendActivations/SendClientActivations',
            splitlearning__pb2.Activations.SerializeToString,
            splitlearning__pb2.Activations.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SendClientGradientsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendGradients = channel.unary_unary(
                '/splitlearning.SendClientGradients/SendGradients',
                request_serializer=splitlearning__pb2.BackPropagate.SerializeToString,
                response_deserializer=splitlearning__pb2.BackPropagate.FromString,
                _registered_method=True)


class SendClientGradientsServicer:
    """Missing associated documentation comment in .proto file."""

    def SendGradients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendClientGradientsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGradients,
                    request_deserializer=splitlearning__pb2.BackPropagate.FromString,
                    response_serializer=splitlearning__pb2.BackPropagate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.SendClientGradients', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearning.SendClientGradients', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SendClientGradients:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SendClientGradients/SendGradients',
            splitlearning__pb2.BackPropagate.SerializeToString,
            splitlearning__pb2.BackPropagate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TestActivationsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestActivations = channel.unary_unary(
                '/splitlearning.TestActivations/TestActivations',
                request_serializer=splitlearning__pb2.Activations.SerializeToString,
                response_deserializer=splitlearning__pb2.Activations.FromString,
                _registered_method=True)


class TestActivationsServicer:
    """Missing associated documentation comment in .proto file."""

    def TestActivations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestActivationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestActivations': grpc.unary_unary_rpc_method_handler(
                    servicer.TestActivations,
                    request_deserializer=splitlearning__pb2.Activations.FromString,
                    response_serializer=splitlearning__pb2.Activations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.TestActivations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearning.TestActivations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestActivations:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestActivations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.TestActivations/TestActivations',
            splitlearning__pb2.Activations.SerializeToString,
            splitlearning__pb2.Activations.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
