# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import splitlearning_pb2 as splitlearning__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in splitlearning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientToServerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendClient1Activations = channel.unary_unary(
                '/splitlearning.ClientToServer/SendClient1Activations',
                request_serializer=splitlearning__pb2.Activations.SerializeToString,
                response_deserializer=splitlearning__pb2.Activations.FromString,
                _registered_method=True)


class ClientToServerServicer:
    """Missing associated documentation comment in .proto file."""

    def SendClient1Activations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientToServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendClient1Activations': grpc.unary_unary_rpc_method_handler(
                    servicer.SendClient1Activations,
                    request_deserializer=splitlearning__pb2.Activations.FromString,
                    response_serializer=splitlearning__pb2.Activations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.ClientToServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearning.ClientToServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientToServer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendClient1Activations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.ClientToServer/SendClient1Activations',
            splitlearning__pb2.Activations.SerializeToString,
            splitlearning__pb2.Activations.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServerToClientStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendServerActivations = channel.unary_unary(
                '/splitlearning.ServerToClient/SendServerActivations',
                request_serializer=splitlearning__pb2.BackPropagate.SerializeToString,
                response_deserializer=splitlearning__pb2.BackPropagate.FromString,
                _registered_method=True)


class ServerToClientServicer:
    """Missing associated documentation comment in .proto file."""

    def SendServerActivations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerToClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendServerActivations': grpc.unary_unary_rpc_method_handler(
                    servicer.SendServerActivations,
                    request_deserializer=splitlearning__pb2.BackPropagate.FromString,
                    response_serializer=splitlearning__pb2.BackPropagate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.ServerToClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearning.ServerToClient', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerToClient:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendServerActivations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.ServerToClient/SendServerActivations',
            splitlearning__pb2.BackPropagate.SerializeToString,
            splitlearning__pb2.BackPropagate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
