syntax = "proto3";

package splitlearning;

message Activations {
    repeated float activations = 1;
    int32 batch_size           = 2;
    int32 client_id            = 3;
    int32 batch_id             = 4;
}

message BackPropagate {
    repeated float gradients = 1;
    int32 batch_size         = 2;
    int32 client_id          = 3;
    int32 batch_id           = 4;
}

service SendActivations {
    rpc SendClientActivations(Activations) returns (Activations) {}
}

service SendClientGradients {
    rpc SendGradients(BackPropagate) returns (BackPropagate) {}
}

service TestActivations {
    rpc TestActivations(Activations) returns (Activations) {}
}